use crate::backend::x64::emit_context::{BlockDescriptor, EmitContext};
use crate::backend::x64::emit_a64;
use crate::backend::x64::a32_emit_a32 as a32;
use crate::backend::x64::emit_data_processing as dp;
use crate::backend::x64::emit_memory;
use crate::backend::x64::emit_exclusive_memory as excl_mem;
use crate::backend::x64::emit_saturation as sat;
use crate::backend::x64::emit_floating_point as fp;
use crate::backend::x64::emit_crc32;
use crate::backend::x64::emit_crypto;
use crate::backend::x64::emit_packed as packed;
use crate::backend::x64::emit_vector_basic as vbasic;
use crate::backend::x64::emit_vector_compare as vcmp;
use crate::backend::x64::emit_vector_shift as vshift;
use crate::backend::x64::emit_vector_multiply as vmul;
use crate::backend::x64::emit_vector_arrangement as varr;
use crate::backend::x64::emit_vector_saturated as vsat;
use crate::backend::x64::emit_vector_misc as vmisc;
use crate::backend::x64::emit_fp_vector as fpv;
use crate::backend::x64::emit_fp_vector_convert as fpvc;
use crate::backend::x64::emit_terminal;
use crate::backend::x64::reg_alloc::RegAlloc;
use crate::ir::block::Block;
use crate::ir::opcode::Opcode;
use crate::ir::value::InstRef;

/// Emit native x86-64 code for an IR block.
///
/// Walks all live instructions, dispatches each opcode to the appropriate
/// emitter function, then emits the block terminal (control flow).
///
/// Returns a `BlockDescriptor` with the entrypoint offset and size.
pub fn emit_block(ctx: &EmitContext, ra: &mut RegAlloc, block: &Block) -> BlockDescriptor {
    let start = ra.asm.size();

    // Emit each instruction
    for (i, inst) in block.instructions.iter().enumerate() {
        if inst.is_tombstone() {
            continue;
        }
        let inst_ref = InstRef(i as u32);

        match inst.opcode {
            // --- Core ---
            Opcode::Void => emit_a64::emit_void(ctx, ra, inst_ref, inst),
            Opcode::Identity => emit_a64::emit_identity(ctx, ra, inst_ref, inst),
            Opcode::Breakpoint => emit_a64::emit_breakpoint(ctx, ra, inst_ref, inst),

            // --- A64 context getters/setters ---
            Opcode::A64SetCheckBit => emit_a64::emit_a64_set_check_bit(ctx, ra, inst_ref, inst),
            Opcode::A64GetCFlag => emit_a64::emit_a64_get_c_flag(ctx, ra, inst_ref, inst),
            Opcode::A64GetNZCVRaw => emit_a64::emit_a64_get_nzcv_raw(ctx, ra, inst_ref, inst),
            Opcode::A64SetNZCVRaw => emit_a64::emit_a64_set_nzcv_raw(ctx, ra, inst_ref, inst),
            Opcode::A64SetNZCV => emit_a64::emit_a64_set_nzcv(ctx, ra, inst_ref, inst),
            Opcode::A64GetW => emit_a64::emit_a64_get_w(ctx, ra, inst_ref, inst),
            Opcode::A64GetX => emit_a64::emit_a64_get_x(ctx, ra, inst_ref, inst),
            Opcode::A64GetS => emit_a64::emit_a64_get_s(ctx, ra, inst_ref, inst),
            Opcode::A64GetD => emit_a64::emit_a64_get_d(ctx, ra, inst_ref, inst),
            Opcode::A64GetQ => emit_a64::emit_a64_get_q(ctx, ra, inst_ref, inst),
            Opcode::A64GetSP => emit_a64::emit_a64_get_sp(ctx, ra, inst_ref, inst),
            Opcode::A64GetFPCR => emit_a64::emit_a64_get_fpcr(ctx, ra, inst_ref, inst),
            Opcode::A64GetFPSR => emit_a64::emit_a64_get_fpsr(ctx, ra, inst_ref, inst),
            Opcode::A64SetW => emit_a64::emit_a64_set_w(ctx, ra, inst_ref, inst),
            Opcode::A64SetX => emit_a64::emit_a64_set_x(ctx, ra, inst_ref, inst),
            Opcode::A64SetS => emit_a64::emit_a64_set_s(ctx, ra, inst_ref, inst),
            Opcode::A64SetD => emit_a64::emit_a64_set_d(ctx, ra, inst_ref, inst),
            Opcode::A64SetQ => emit_a64::emit_a64_set_q(ctx, ra, inst_ref, inst),
            Opcode::A64SetSP => emit_a64::emit_a64_set_sp(ctx, ra, inst_ref, inst),
            Opcode::A64SetPC => emit_a64::emit_a64_set_pc(ctx, ra, inst_ref, inst),
            Opcode::A64SetFPCR => emit_a64::emit_a64_set_fpcr(ctx, ra, inst_ref, inst),
            Opcode::A64SetFPSR => emit_a64::emit_a64_set_fpsr(ctx, ra, inst_ref, inst),
            Opcode::A64CallSupervisor => emit_a64::emit_a64_call_supervisor(ctx, ra, inst_ref, inst),
            Opcode::A64ExceptionRaised => emit_a64::emit_a64_exception_raised(ctx, ra, inst_ref, inst),
            Opcode::A64DataCacheOperationRaised => emit_a64::emit_a64_data_cache_operation_raised(ctx, ra, inst_ref, inst),
            Opcode::A64InstructionCacheOperationRaised => emit_a64::emit_a64_instruction_cache_operation_raised(ctx, ra, inst_ref, inst),
            Opcode::A64DataSynchronizationBarrier => emit_a64::emit_a64_dsb(ctx, ra, inst_ref, inst),
            Opcode::A64DataMemoryBarrier => emit_a64::emit_a64_dmb(ctx, ra, inst_ref, inst),
            Opcode::A64InstructionSynchronizationBarrier => emit_a64::emit_a64_isb(ctx, ra, inst_ref, inst),
            Opcode::A64GetCNTFRQ => emit_a64::emit_a64_get_cntfrq(ctx, ra, inst_ref, inst),
            Opcode::A64GetCNTPCT => emit_a64::emit_a64_get_cntpct(ctx, ra, inst_ref, inst),
            Opcode::A64GetCTR => emit_a64::emit_a64_get_ctr(ctx, ra, inst_ref, inst),
            Opcode::A64GetDCZID => emit_a64::emit_a64_get_dczid(ctx, ra, inst_ref, inst),
            Opcode::A64GetTPIDR => emit_a64::emit_a64_get_tpidr(ctx, ra, inst_ref, inst),
            Opcode::A64SetTPIDR => emit_a64::emit_a64_set_tpidr(ctx, ra, inst_ref, inst),
            Opcode::A64GetTPIDRRO => emit_a64::emit_a64_get_tpidrro(ctx, ra, inst_ref, inst),

            // --- RSB ---
            Opcode::PushRSB => emit_a64::emit_push_rsb(ctx, ra, inst_ref, inst),

            // --- Flags / pseudo-ops ---
            Opcode::GetCarryFromOp => emit_a64::emit_get_carry_from_op(ctx, ra, inst_ref, inst),
            Opcode::GetOverflowFromOp => emit_a64::emit_get_overflow_from_op(ctx, ra, inst_ref, inst),
            Opcode::GetNZCVFromOp => emit_a64::emit_get_nzcv_from_op(ctx, ra, inst_ref, inst),
            Opcode::GetNZFromOp => emit_a64::emit_get_nz_from_op(ctx, ra, inst_ref, inst),
            Opcode::GetUpperFromOp => emit_a64::emit_get_upper_from_op(ctx, ra, inst_ref, inst),
            Opcode::GetLowerFromOp => emit_a64::emit_get_lower_from_op(ctx, ra, inst_ref, inst),
            Opcode::GetCFlagFromNZCV => emit_a64::emit_get_c_flag_from_nzcv(ctx, ra, inst_ref, inst),
            Opcode::NZCVFromPackedFlags => emit_a64::emit_nzcv_from_packed_flags(ctx, ra, inst_ref, inst),

            // --- ALU: packing/extraction ---
            Opcode::Pack2x32To1x64 => dp::emit_pack_2x32_to_1x64(ctx, ra, inst_ref, inst),
            Opcode::Pack2x64To1x128 => fp::emit_pack_2x64_to_1x128(ctx, ra, inst_ref, inst),
            Opcode::LeastSignificantWord => dp::emit_least_significant_word(ctx, ra, inst_ref, inst),
            Opcode::MostSignificantWord => dp::emit_most_significant_word(ctx, ra, inst_ref, inst),
            Opcode::LeastSignificantHalf => dp::emit_least_significant_half(ctx, ra, inst_ref, inst),
            Opcode::LeastSignificantByte => dp::emit_least_significant_byte(ctx, ra, inst_ref, inst),
            Opcode::MostSignificantBit => dp::emit_most_significant_bit(ctx, ra, inst_ref, inst),

            // --- ALU: test/compare ---
            Opcode::IsZero32 => dp::emit_is_zero32(ctx, ra, inst_ref, inst),
            Opcode::IsZero64 => dp::emit_is_zero64(ctx, ra, inst_ref, inst),
            Opcode::TestBit => dp::emit_test_bit(ctx, ra, inst_ref, inst),

            // --- ALU: conditional select ---
            Opcode::ConditionalSelect32 => dp::emit_conditional_select32(ctx, ra, inst_ref, inst),
            Opcode::ConditionalSelect64 => dp::emit_conditional_select64(ctx, ra, inst_ref, inst),
            Opcode::ConditionalSelectNZCV => dp::emit_conditional_select_nzcv(ctx, ra, inst_ref, inst),

            // --- ALU: shifts (dynamic) ---
            Opcode::LogicalShiftLeft32 => dp::emit_logical_shift_left32(ctx, ra, inst_ref, inst),
            Opcode::LogicalShiftLeft64 => dp::emit_logical_shift_left64(ctx, ra, inst_ref, inst),
            Opcode::LogicalShiftRight32 => dp::emit_logical_shift_right32(ctx, ra, inst_ref, inst),
            Opcode::LogicalShiftRight64 => dp::emit_logical_shift_right64(ctx, ra, inst_ref, inst),
            Opcode::ArithmeticShiftRight32 => dp::emit_arithmetic_shift_right32(ctx, ra, inst_ref, inst),
            Opcode::ArithmeticShiftRight64 => dp::emit_arithmetic_shift_right64(ctx, ra, inst_ref, inst),
            Opcode::RotateRight32 => dp::emit_rotate_right32(ctx, ra, inst_ref, inst),
            Opcode::RotateRight64 => dp::emit_rotate_right64(ctx, ra, inst_ref, inst),
            Opcode::RotateRightExtended => dp::emit_rotate_right_extended(ctx, ra, inst_ref, inst),

            // --- ALU: shifts (masked, no clamping) ---
            Opcode::LogicalShiftLeftMasked32 => dp::emit_logical_shift_left_masked32(ctx, ra, inst_ref, inst),
            Opcode::LogicalShiftLeftMasked64 => dp::emit_logical_shift_left_masked64(ctx, ra, inst_ref, inst),
            Opcode::LogicalShiftRightMasked32 => dp::emit_logical_shift_right_masked32(ctx, ra, inst_ref, inst),
            Opcode::LogicalShiftRightMasked64 => dp::emit_logical_shift_right_masked64(ctx, ra, inst_ref, inst),
            Opcode::ArithmeticShiftRightMasked32 => dp::emit_arithmetic_shift_right_masked32(ctx, ra, inst_ref, inst),
            Opcode::ArithmeticShiftRightMasked64 => dp::emit_arithmetic_shift_right_masked64(ctx, ra, inst_ref, inst),
            Opcode::RotateRightMasked32 => dp::emit_rotate_right_masked32(ctx, ra, inst_ref, inst),
            Opcode::RotateRightMasked64 => dp::emit_rotate_right_masked64(ctx, ra, inst_ref, inst),

            // --- ALU: arithmetic ---
            Opcode::Add32 => dp::emit_add32(ctx, ra, inst_ref, inst),
            Opcode::Add64 => dp::emit_add64(ctx, ra, inst_ref, inst),
            Opcode::Sub32 => dp::emit_sub32(ctx, ra, inst_ref, inst),
            Opcode::Sub64 => dp::emit_sub64(ctx, ra, inst_ref, inst),
            Opcode::Mul32 => dp::emit_mul32(ctx, ra, inst_ref, inst),
            Opcode::Mul64 => dp::emit_mul64(ctx, ra, inst_ref, inst),
            Opcode::SignedMultiplyHigh64 => dp::emit_signed_multiply_high_64(ctx, ra, inst_ref, inst),
            Opcode::UnsignedMultiplyHigh64 => dp::emit_unsigned_multiply_high_64(ctx, ra, inst_ref, inst),
            Opcode::UnsignedDiv32 => dp::emit_unsigned_div32(ctx, ra, inst_ref, inst),
            Opcode::UnsignedDiv64 => dp::emit_unsigned_div64(ctx, ra, inst_ref, inst),
            Opcode::SignedDiv32 => dp::emit_signed_div32(ctx, ra, inst_ref, inst),
            Opcode::SignedDiv64 => dp::emit_signed_div64(ctx, ra, inst_ref, inst),

            // --- ALU: logical ---
            Opcode::And32 => dp::emit_and32(ctx, ra, inst_ref, inst),
            Opcode::And64 => dp::emit_and64(ctx, ra, inst_ref, inst),
            Opcode::AndNot32 => dp::emit_and_not32(ctx, ra, inst_ref, inst),
            Opcode::AndNot64 => dp::emit_and_not64(ctx, ra, inst_ref, inst),
            Opcode::Eor32 => dp::emit_eor32(ctx, ra, inst_ref, inst),
            Opcode::Eor64 => dp::emit_eor64(ctx, ra, inst_ref, inst),
            Opcode::Or32 => dp::emit_or32(ctx, ra, inst_ref, inst),
            Opcode::Or64 => dp::emit_or64(ctx, ra, inst_ref, inst),
            Opcode::Not32 => dp::emit_not32(ctx, ra, inst_ref, inst),
            Opcode::Not64 => dp::emit_not64(ctx, ra, inst_ref, inst),

            // --- ALU: extensions ---
            Opcode::SignExtendByteToWord => dp::emit_sign_extend_byte_to_word(ctx, ra, inst_ref, inst),
            Opcode::SignExtendHalfToWord => dp::emit_sign_extend_half_to_word(ctx, ra, inst_ref, inst),
            Opcode::SignExtendByteToLong => dp::emit_sign_extend_byte_to_long(ctx, ra, inst_ref, inst),
            Opcode::SignExtendHalfToLong => dp::emit_sign_extend_half_to_long(ctx, ra, inst_ref, inst),
            Opcode::SignExtendWordToLong => dp::emit_sign_extend_word_to_long(ctx, ra, inst_ref, inst),
            Opcode::ZeroExtendByteToWord => dp::emit_zero_extend_byte_to_word(ctx, ra, inst_ref, inst),
            Opcode::ZeroExtendHalfToWord => dp::emit_zero_extend_half_to_word(ctx, ra, inst_ref, inst),
            Opcode::ZeroExtendByteToLong => dp::emit_zero_extend_byte_to_long(ctx, ra, inst_ref, inst),
            Opcode::ZeroExtendHalfToLong => dp::emit_zero_extend_half_to_long(ctx, ra, inst_ref, inst),
            Opcode::ZeroExtendWordToLong => dp::emit_zero_extend_word_to_long(ctx, ra, inst_ref, inst),
            Opcode::ZeroExtendLongToQuad => dp::emit_zero_extend_long_to_quad(ctx, ra, inst_ref, inst),

            // --- ALU: byte reverse ---
            Opcode::ByteReverseWord => dp::emit_byte_reverse_word(ctx, ra, inst_ref, inst),
            Opcode::ByteReverseHalf => dp::emit_byte_reverse_half(ctx, ra, inst_ref, inst),
            Opcode::ByteReverseDual => dp::emit_byte_reverse_dual(ctx, ra, inst_ref, inst),

            // --- ALU: bit counting ---
            Opcode::CountLeadingZeros32 => dp::emit_count_leading_zeros32(ctx, ra, inst_ref, inst),
            Opcode::CountLeadingZeros64 => dp::emit_count_leading_zeros64(ctx, ra, inst_ref, inst),

            // --- ALU: extract/replicate ---
            Opcode::ExtractRegister32 => dp::emit_extract_register32(ctx, ra, inst_ref, inst),
            Opcode::ExtractRegister64 => dp::emit_extract_register64(ctx, ra, inst_ref, inst),
            Opcode::ReplicateBit32 => dp::emit_replicate_bit32(ctx, ra, inst_ref, inst),
            Opcode::ReplicateBit64 => dp::emit_replicate_bit64(ctx, ra, inst_ref, inst),

            // --- Saturated: max/min ---
            Opcode::MaxSigned32 => dp::emit_max_signed32(ctx, ra, inst_ref, inst),
            Opcode::MaxSigned64 => dp::emit_max_signed64(ctx, ra, inst_ref, inst),
            Opcode::MaxUnsigned32 => dp::emit_max_unsigned32(ctx, ra, inst_ref, inst),
            Opcode::MaxUnsigned64 => dp::emit_max_unsigned64(ctx, ra, inst_ref, inst),
            Opcode::MinSigned32 => dp::emit_min_signed32(ctx, ra, inst_ref, inst),
            Opcode::MinSigned64 => dp::emit_min_signed64(ctx, ra, inst_ref, inst),
            Opcode::MinUnsigned32 => dp::emit_min_unsigned32(ctx, ra, inst_ref, inst),
            Opcode::MinUnsigned64 => dp::emit_min_unsigned64(ctx, ra, inst_ref, inst),

            // --- Memory access ---
            Opcode::A64ReadMemory8 => emit_memory::emit_a64_read_memory_8(ctx, ra, inst_ref, inst),
            Opcode::A64ReadMemory16 => emit_memory::emit_a64_read_memory_16(ctx, ra, inst_ref, inst),
            Opcode::A64ReadMemory32 => emit_memory::emit_a64_read_memory_32(ctx, ra, inst_ref, inst),
            Opcode::A64ReadMemory64 => emit_memory::emit_a64_read_memory_64(ctx, ra, inst_ref, inst),
            Opcode::A64ReadMemory128 => emit_memory::emit_a64_read_memory_128(ctx, ra, inst_ref, inst),
            Opcode::A64WriteMemory8 => emit_memory::emit_a64_write_memory_8(ctx, ra, inst_ref, inst),
            Opcode::A64WriteMemory16 => emit_memory::emit_a64_write_memory_16(ctx, ra, inst_ref, inst),
            Opcode::A64WriteMemory32 => emit_memory::emit_a64_write_memory_32(ctx, ra, inst_ref, inst),
            Opcode::A64WriteMemory64 => emit_memory::emit_a64_write_memory_64(ctx, ra, inst_ref, inst),
            Opcode::A64WriteMemory128 => emit_memory::emit_a64_write_memory_128(ctx, ra, inst_ref, inst),

            // --- Exclusive memory access ---
            Opcode::A64ClearExclusive => excl_mem::emit_a64_clear_exclusive(ctx, ra, inst_ref, inst),
            Opcode::A64ExclusiveReadMemory8 => excl_mem::emit_a64_exclusive_read_memory_8(ctx, ra, inst_ref, inst),
            Opcode::A64ExclusiveReadMemory16 => excl_mem::emit_a64_exclusive_read_memory_16(ctx, ra, inst_ref, inst),
            Opcode::A64ExclusiveReadMemory32 => excl_mem::emit_a64_exclusive_read_memory_32(ctx, ra, inst_ref, inst),
            Opcode::A64ExclusiveReadMemory64 => excl_mem::emit_a64_exclusive_read_memory_64(ctx, ra, inst_ref, inst),
            Opcode::A64ExclusiveReadMemory128 => excl_mem::emit_a64_exclusive_read_memory_128(ctx, ra, inst_ref, inst),
            Opcode::A64ExclusiveWriteMemory8 => excl_mem::emit_a64_exclusive_write_memory_8(ctx, ra, inst_ref, inst),
            Opcode::A64ExclusiveWriteMemory16 => excl_mem::emit_a64_exclusive_write_memory_16(ctx, ra, inst_ref, inst),
            Opcode::A64ExclusiveWriteMemory32 => excl_mem::emit_a64_exclusive_write_memory_32(ctx, ra, inst_ref, inst),
            Opcode::A64ExclusiveWriteMemory64 => excl_mem::emit_a64_exclusive_write_memory_64(ctx, ra, inst_ref, inst),
            Opcode::A64ExclusiveWriteMemory128 => excl_mem::emit_a64_exclusive_write_memory_128(ctx, ra, inst_ref, inst),

            // --- Saturated arithmetic ---
            Opcode::SignedSaturatedAdd8 => sat::emit_signed_saturated_add8(ctx, ra, inst_ref, inst),
            Opcode::SignedSaturatedAdd16 => sat::emit_signed_saturated_add16(ctx, ra, inst_ref, inst),
            Opcode::SignedSaturatedAdd32 => sat::emit_signed_saturated_add32(ctx, ra, inst_ref, inst),
            Opcode::SignedSaturatedAdd64 => sat::emit_signed_saturated_add64(ctx, ra, inst_ref, inst),
            Opcode::SignedSaturatedSub8 => sat::emit_signed_saturated_sub8(ctx, ra, inst_ref, inst),
            Opcode::SignedSaturatedSub16 => sat::emit_signed_saturated_sub16(ctx, ra, inst_ref, inst),
            Opcode::SignedSaturatedSub32 => sat::emit_signed_saturated_sub32(ctx, ra, inst_ref, inst),
            Opcode::SignedSaturatedSub64 => sat::emit_signed_saturated_sub64(ctx, ra, inst_ref, inst),
            Opcode::UnsignedSaturatedAdd8 => sat::emit_unsigned_saturated_add8(ctx, ra, inst_ref, inst),
            Opcode::UnsignedSaturatedAdd16 => sat::emit_unsigned_saturated_add16(ctx, ra, inst_ref, inst),
            Opcode::UnsignedSaturatedAdd32 => sat::emit_unsigned_saturated_add32(ctx, ra, inst_ref, inst),
            Opcode::UnsignedSaturatedAdd64 => sat::emit_unsigned_saturated_add64(ctx, ra, inst_ref, inst),
            Opcode::UnsignedSaturatedSub8 => sat::emit_unsigned_saturated_sub8(ctx, ra, inst_ref, inst),
            Opcode::UnsignedSaturatedSub16 => sat::emit_unsigned_saturated_sub16(ctx, ra, inst_ref, inst),
            Opcode::UnsignedSaturatedSub32 => sat::emit_unsigned_saturated_sub32(ctx, ra, inst_ref, inst),
            Opcode::UnsignedSaturatedSub64 => sat::emit_unsigned_saturated_sub64(ctx, ra, inst_ref, inst),
            Opcode::SignedSaturation => sat::emit_signed_saturation(ctx, ra, inst_ref, inst),
            Opcode::UnsignedSaturation => sat::emit_unsigned_saturation(ctx, ra, inst_ref, inst),
            Opcode::SignedSaturatedDoublingMultiplyReturnHigh16 => sat::emit_signed_saturated_doubling_multiply_return_high16(ctx, ra, inst_ref, inst),
            Opcode::SignedSaturatedDoublingMultiplyReturnHigh32 => sat::emit_signed_saturated_doubling_multiply_return_high32(ctx, ra, inst_ref, inst),

            // --- FP scalar arithmetic ---
            Opcode::FPAdd32 => fp::emit_fp_add32(ctx, ra, inst_ref, inst),
            Opcode::FPAdd64 => fp::emit_fp_add64(ctx, ra, inst_ref, inst),
            Opcode::FPSub32 => fp::emit_fp_sub32(ctx, ra, inst_ref, inst),
            Opcode::FPSub64 => fp::emit_fp_sub64(ctx, ra, inst_ref, inst),
            Opcode::FPMul32 => fp::emit_fp_mul32(ctx, ra, inst_ref, inst),
            Opcode::FPMul64 => fp::emit_fp_mul64(ctx, ra, inst_ref, inst),
            Opcode::FPDiv32 => fp::emit_fp_div32(ctx, ra, inst_ref, inst),
            Opcode::FPDiv64 => fp::emit_fp_div64(ctx, ra, inst_ref, inst),
            Opcode::FPSqrt32 => fp::emit_fp_sqrt32(ctx, ra, inst_ref, inst),
            Opcode::FPSqrt64 => fp::emit_fp_sqrt64(ctx, ra, inst_ref, inst),
            Opcode::FPAbs32 => fp::emit_fp_abs32(ctx, ra, inst_ref, inst),
            Opcode::FPAbs64 => fp::emit_fp_abs64(ctx, ra, inst_ref, inst),
            Opcode::FPAbs16 => fp::emit_fp_abs16(ctx, ra, inst_ref, inst),
            Opcode::FPNeg32 => fp::emit_fp_neg32(ctx, ra, inst_ref, inst),
            Opcode::FPNeg64 => fp::emit_fp_neg64(ctx, ra, inst_ref, inst),
            Opcode::FPNeg16 => fp::emit_fp_neg16(ctx, ra, inst_ref, inst),
            Opcode::FPMax32 => fp::emit_fp_max32(ctx, ra, inst_ref, inst),
            Opcode::FPMax64 => fp::emit_fp_max64(ctx, ra, inst_ref, inst),
            Opcode::FPMin32 => fp::emit_fp_min32(ctx, ra, inst_ref, inst),
            Opcode::FPMin64 => fp::emit_fp_min64(ctx, ra, inst_ref, inst),
            Opcode::FPMaxNumeric32 => fp::emit_fp_max_numeric32(ctx, ra, inst_ref, inst),
            Opcode::FPMaxNumeric64 => fp::emit_fp_max_numeric64(ctx, ra, inst_ref, inst),
            Opcode::FPMinNumeric32 => fp::emit_fp_min_numeric32(ctx, ra, inst_ref, inst),
            Opcode::FPMinNumeric64 => fp::emit_fp_min_numeric64(ctx, ra, inst_ref, inst),
            Opcode::FPCompare32 => fp::emit_fp_compare32(ctx, ra, inst_ref, inst),
            Opcode::FPCompare64 => fp::emit_fp_compare64(ctx, ra, inst_ref, inst),
            Opcode::FPRoundInt32 => fp::emit_fp_round_int32(ctx, ra, inst_ref, inst),
            Opcode::FPRoundInt64 => fp::emit_fp_round_int64(ctx, ra, inst_ref, inst),
            Opcode::FPRoundInt16 => fp::emit_fp_round_int16(ctx, ra, inst_ref, inst),

            // --- FP fused multiply-add/sub ---
            Opcode::FPMulAdd32 => fp::emit_fp_mul_add32(ctx, ra, inst_ref, inst),
            Opcode::FPMulAdd64 => fp::emit_fp_mul_add64(ctx, ra, inst_ref, inst),
            Opcode::FPMulSub32 => fp::emit_fp_mul_sub32(ctx, ra, inst_ref, inst),
            Opcode::FPMulSub64 => fp::emit_fp_mul_sub64(ctx, ra, inst_ref, inst),
            Opcode::FPMulAdd16 => fp::emit_fp_mul_add16(ctx, ra, inst_ref, inst),
            Opcode::FPMulSub16 => fp::emit_fp_mul_sub16(ctx, ra, inst_ref, inst),

            // --- FP conversions ---
            Opcode::FPSingleToDouble => fp::emit_fp_single_to_double(ctx, ra, inst_ref, inst),
            Opcode::FPDoubleToSingle => fp::emit_fp_double_to_single(ctx, ra, inst_ref, inst),
            Opcode::FPHalfToSingle => fp::emit_fp_half_to_single(ctx, ra, inst_ref, inst),
            Opcode::FPHalfToDouble => fp::emit_fp_half_to_double(ctx, ra, inst_ref, inst),
            Opcode::FPSingleToHalf => fp::emit_fp_single_to_half(ctx, ra, inst_ref, inst),
            Opcode::FPDoubleToHalf => fp::emit_fp_double_to_half(ctx, ra, inst_ref, inst),

            // --- FP multiply extended ---
            Opcode::FPMulX32 => fp::emit_fp_mul_x32(ctx, ra, inst_ref, inst),
            Opcode::FPMulX64 => fp::emit_fp_mul_x64(ctx, ra, inst_ref, inst),

            // --- FP reciprocal/sqrt estimates ---
            Opcode::FPRecipEstimate16 => fp::emit_fp_recip_estimate16(ctx, ra, inst_ref, inst),
            Opcode::FPRecipEstimate32 => fp::emit_fp_recip_estimate32(ctx, ra, inst_ref, inst),
            Opcode::FPRecipEstimate64 => fp::emit_fp_recip_estimate64(ctx, ra, inst_ref, inst),
            Opcode::FPRecipExponent16 => fp::emit_fp_recip_exponent16(ctx, ra, inst_ref, inst),
            Opcode::FPRecipExponent32 => fp::emit_fp_recip_exponent32(ctx, ra, inst_ref, inst),
            Opcode::FPRecipExponent64 => fp::emit_fp_recip_exponent64(ctx, ra, inst_ref, inst),
            Opcode::FPRecipStepFused16 => fp::emit_fp_recip_step_fused16(ctx, ra, inst_ref, inst),
            Opcode::FPRecipStepFused32 => fp::emit_fp_recip_step_fused32(ctx, ra, inst_ref, inst),
            Opcode::FPRecipStepFused64 => fp::emit_fp_recip_step_fused64(ctx, ra, inst_ref, inst),
            Opcode::FPRSqrtEstimate16 => fp::emit_fp_rsqrt_estimate16(ctx, ra, inst_ref, inst),
            Opcode::FPRSqrtEstimate32 => fp::emit_fp_rsqrt_estimate32(ctx, ra, inst_ref, inst),
            Opcode::FPRSqrtEstimate64 => fp::emit_fp_rsqrt_estimate64(ctx, ra, inst_ref, inst),
            Opcode::FPRSqrtStepFused16 => fp::emit_fp_rsqrt_step_fused16(ctx, ra, inst_ref, inst),
            Opcode::FPRSqrtStepFused32 => fp::emit_fp_rsqrt_step_fused32(ctx, ra, inst_ref, inst),
            Opcode::FPRSqrtStepFused64 => fp::emit_fp_rsqrt_step_fused64(ctx, ra, inst_ref, inst),

            // --- FP fixed-point conversions ---
            Opcode::FPFixedS32ToSingle => fp::emit_fp_fixed_s32_to_single(ctx, ra, inst_ref, inst),
            Opcode::FPFixedS32ToDouble => fp::emit_fp_fixed_s32_to_double(ctx, ra, inst_ref, inst),
            Opcode::FPFixedU32ToSingle => fp::emit_fp_fixed_u32_to_single(ctx, ra, inst_ref, inst),
            Opcode::FPFixedU32ToDouble => fp::emit_fp_fixed_u32_to_double(ctx, ra, inst_ref, inst),
            Opcode::FPFixedS64ToSingle => fp::emit_fp_fixed_s64_to_single(ctx, ra, inst_ref, inst),
            Opcode::FPFixedS64ToDouble => fp::emit_fp_fixed_s64_to_double(ctx, ra, inst_ref, inst),
            Opcode::FPFixedU64ToSingle => fp::emit_fp_fixed_u64_to_single(ctx, ra, inst_ref, inst),
            Opcode::FPFixedU64ToDouble => fp::emit_fp_fixed_u64_to_double(ctx, ra, inst_ref, inst),
            Opcode::FPSingleToFixedS32 => fp::emit_fp_single_to_fixed_s32(ctx, ra, inst_ref, inst),
            Opcode::FPSingleToFixedS64 => fp::emit_fp_single_to_fixed_s64(ctx, ra, inst_ref, inst),
            Opcode::FPDoubleToFixedS32 => fp::emit_fp_double_to_fixed_s32(ctx, ra, inst_ref, inst),
            Opcode::FPDoubleToFixedS64 => fp::emit_fp_double_to_fixed_s64(ctx, ra, inst_ref, inst),
            Opcode::FPSingleToFixedU32 => fp::emit_fp_single_to_fixed_u32(ctx, ra, inst_ref, inst),
            Opcode::FPSingleToFixedU64 => fp::emit_fp_single_to_fixed_u64(ctx, ra, inst_ref, inst),
            Opcode::FPDoubleToFixedU32 => fp::emit_fp_double_to_fixed_u32(ctx, ra, inst_ref, inst),
            Opcode::FPDoubleToFixedU64 => fp::emit_fp_double_to_fixed_u64(ctx, ra, inst_ref, inst),
            Opcode::FPFixedU16ToSingle => fp::emit_fp_fixed_u16_to_single(ctx, ra, inst_ref, inst),
            Opcode::FPFixedS16ToSingle => fp::emit_fp_fixed_s16_to_single(ctx, ra, inst_ref, inst),
            Opcode::FPFixedU16ToDouble => fp::emit_fp_fixed_u16_to_double(ctx, ra, inst_ref, inst),
            Opcode::FPFixedS16ToDouble => fp::emit_fp_fixed_s16_to_double(ctx, ra, inst_ref, inst),

            // --- FP half/16-bit fixed-point ---
            Opcode::FPHalfToFixedS16 => fp::emit_fp_half_to_fixed_s16(ctx, ra, inst_ref, inst),
            Opcode::FPHalfToFixedS32 => fp::emit_fp_half_to_fixed_s32(ctx, ra, inst_ref, inst),
            Opcode::FPHalfToFixedS64 => fp::emit_fp_half_to_fixed_s64(ctx, ra, inst_ref, inst),
            Opcode::FPHalfToFixedU16 => fp::emit_fp_half_to_fixed_u16(ctx, ra, inst_ref, inst),
            Opcode::FPHalfToFixedU32 => fp::emit_fp_half_to_fixed_u32(ctx, ra, inst_ref, inst),
            Opcode::FPHalfToFixedU64 => fp::emit_fp_half_to_fixed_u64(ctx, ra, inst_ref, inst),
            Opcode::FPDoubleToFixedS16 => fp::emit_fp_double_to_fixed_s16(ctx, ra, inst_ref, inst),
            Opcode::FPDoubleToFixedU16 => fp::emit_fp_double_to_fixed_u16(ctx, ra, inst_ref, inst),
            Opcode::FPSingleToFixedS16 => fp::emit_fp_single_to_fixed_s16(ctx, ra, inst_ref, inst),
            Opcode::FPSingleToFixedU16 => fp::emit_fp_single_to_fixed_u16(ctx, ra, inst_ref, inst),

            // --- CRC32 ---
            Opcode::CRC32Castagnoli8 => emit_crc32::emit_crc32_castagnoli8(ctx, ra, inst_ref, inst),
            Opcode::CRC32Castagnoli16 => emit_crc32::emit_crc32_castagnoli16(ctx, ra, inst_ref, inst),
            Opcode::CRC32Castagnoli32 => emit_crc32::emit_crc32_castagnoli32(ctx, ra, inst_ref, inst),
            Opcode::CRC32Castagnoli64 => emit_crc32::emit_crc32_castagnoli64(ctx, ra, inst_ref, inst),
            Opcode::CRC32ISO8 => emit_crc32::emit_crc32_iso8(ctx, ra, inst_ref, inst),
            Opcode::CRC32ISO16 => emit_crc32::emit_crc32_iso16(ctx, ra, inst_ref, inst),
            Opcode::CRC32ISO32 => emit_crc32::emit_crc32_iso32(ctx, ra, inst_ref, inst),
            Opcode::CRC32ISO64 => emit_crc32::emit_crc32_iso64(ctx, ra, inst_ref, inst),

            // --- Crypto: AES ---
            Opcode::AESEncryptSingleRound => emit_crypto::emit_aes_encrypt_single_round(ctx, ra, inst_ref, inst),
            Opcode::AESDecryptSingleRound => emit_crypto::emit_aes_decrypt_single_round(ctx, ra, inst_ref, inst),
            Opcode::AESInverseMixColumns => emit_crypto::emit_aes_inverse_mix_columns(ctx, ra, inst_ref, inst),
            Opcode::AESMixColumns => emit_crypto::emit_aes_mix_columns(ctx, ra, inst_ref, inst),

            // --- Crypto: SHA/SM4 ---
            Opcode::SHA256Hash => emit_crypto::emit_sha256_hash(ctx, ra, inst_ref, inst),
            Opcode::SHA256MessageSchedule0 => emit_crypto::emit_sha256_message_schedule_0(ctx, ra, inst_ref, inst),
            Opcode::SHA256MessageSchedule1 => emit_crypto::emit_sha256_message_schedule_1(ctx, ra, inst_ref, inst),
            Opcode::SM4AccessSubstitutionBox => emit_crypto::emit_sm4_access_substitution_box(ctx, ra, inst_ref, inst),

            // --- Packed operations ---
            Opcode::PackedAddU8 => packed::emit_packed_add_u8(ctx, ra, inst_ref, inst),
            Opcode::PackedAddS8 => packed::emit_packed_add_s8(ctx, ra, inst_ref, inst),
            Opcode::PackedAddU16 => packed::emit_packed_add_u16(ctx, ra, inst_ref, inst),
            Opcode::PackedAddS16 => packed::emit_packed_add_s16(ctx, ra, inst_ref, inst),
            Opcode::PackedSubU8 => packed::emit_packed_sub_u8(ctx, ra, inst_ref, inst),
            Opcode::PackedSubS8 => packed::emit_packed_sub_s8(ctx, ra, inst_ref, inst),
            Opcode::PackedSubU16 => packed::emit_packed_sub_u16(ctx, ra, inst_ref, inst),
            Opcode::PackedSubS16 => packed::emit_packed_sub_s16(ctx, ra, inst_ref, inst),
            Opcode::PackedSaturatedAddU8 => packed::emit_packed_saturated_add_u8(ctx, ra, inst_ref, inst),
            Opcode::PackedSaturatedAddS8 => packed::emit_packed_saturated_add_s8(ctx, ra, inst_ref, inst),
            Opcode::PackedSaturatedAddU16 => packed::emit_packed_saturated_add_u16(ctx, ra, inst_ref, inst),
            Opcode::PackedSaturatedAddS16 => packed::emit_packed_saturated_add_s16(ctx, ra, inst_ref, inst),
            Opcode::PackedSaturatedSubU8 => packed::emit_packed_saturated_sub_u8(ctx, ra, inst_ref, inst),
            Opcode::PackedSaturatedSubS8 => packed::emit_packed_saturated_sub_s8(ctx, ra, inst_ref, inst),
            Opcode::PackedSaturatedSubU16 => packed::emit_packed_saturated_sub_u16(ctx, ra, inst_ref, inst),
            Opcode::PackedSaturatedSubS16 => packed::emit_packed_saturated_sub_s16(ctx, ra, inst_ref, inst),
            Opcode::PackedAbsDiffSumS8 => packed::emit_packed_abs_diff_sum_s8(ctx, ra, inst_ref, inst),
            Opcode::PackedSelect => packed::emit_packed_select(ctx, ra, inst_ref, inst),
            Opcode::PackedAddSubU16 => packed::emit_packed_add_sub_u16(ctx, ra, inst_ref, inst),
            Opcode::PackedAddSubS16 => packed::emit_packed_add_sub_s16(ctx, ra, inst_ref, inst),
            Opcode::PackedSubAddU16 => packed::emit_packed_sub_add_u16(ctx, ra, inst_ref, inst),
            Opcode::PackedSubAddS16 => packed::emit_packed_sub_add_s16(ctx, ra, inst_ref, inst),
            Opcode::PackedHalvingAddU8 => packed::emit_packed_halving_add_u8(ctx, ra, inst_ref, inst),
            Opcode::PackedHalvingAddS8 => packed::emit_packed_halving_add_s8(ctx, ra, inst_ref, inst),
            Opcode::PackedHalvingAddU16 => packed::emit_packed_halving_add_u16(ctx, ra, inst_ref, inst),
            Opcode::PackedHalvingAddS16 => packed::emit_packed_halving_add_s16(ctx, ra, inst_ref, inst),
            Opcode::PackedHalvingSubU8 => packed::emit_packed_halving_sub_u8(ctx, ra, inst_ref, inst),
            Opcode::PackedHalvingSubS8 => packed::emit_packed_halving_sub_s8(ctx, ra, inst_ref, inst),
            Opcode::PackedHalvingSubU16 => packed::emit_packed_halving_sub_u16(ctx, ra, inst_ref, inst),
            Opcode::PackedHalvingSubS16 => packed::emit_packed_halving_sub_s16(ctx, ra, inst_ref, inst),
            Opcode::PackedHalvingAddSubU16 => packed::emit_packed_halving_add_sub_u16(ctx, ra, inst_ref, inst),
            Opcode::PackedHalvingAddSubS16 => packed::emit_packed_halving_add_sub_s16(ctx, ra, inst_ref, inst),
            Opcode::PackedHalvingSubAddU16 => packed::emit_packed_halving_sub_add_u16(ctx, ra, inst_ref, inst),
            Opcode::PackedHalvingSubAddS16 => packed::emit_packed_halving_sub_add_s16(ctx, ra, inst_ref, inst),

            // --- Vector basic ---
            Opcode::VectorAdd8 => vbasic::emit_vector_add8(ctx, ra, inst_ref, inst),
            Opcode::VectorAdd16 => vbasic::emit_vector_add16(ctx, ra, inst_ref, inst),
            Opcode::VectorAdd32 => vbasic::emit_vector_add32(ctx, ra, inst_ref, inst),
            Opcode::VectorAdd64 => vbasic::emit_vector_add64(ctx, ra, inst_ref, inst),
            Opcode::VectorSub8 => vbasic::emit_vector_sub8(ctx, ra, inst_ref, inst),
            Opcode::VectorSub16 => vbasic::emit_vector_sub16(ctx, ra, inst_ref, inst),
            Opcode::VectorSub32 => vbasic::emit_vector_sub32(ctx, ra, inst_ref, inst),
            Opcode::VectorSub64 => vbasic::emit_vector_sub64(ctx, ra, inst_ref, inst),
            Opcode::VectorAnd => vbasic::emit_vector_and(ctx, ra, inst_ref, inst),
            Opcode::VectorAndNot => vbasic::emit_vector_and_not(ctx, ra, inst_ref, inst),
            Opcode::VectorOr => vbasic::emit_vector_or(ctx, ra, inst_ref, inst),
            Opcode::VectorEor => vbasic::emit_vector_eor(ctx, ra, inst_ref, inst),
            Opcode::VectorNot => vbasic::emit_vector_not(ctx, ra, inst_ref, inst),
            Opcode::VectorAbs8 => vbasic::emit_vector_abs8(ctx, ra, inst_ref, inst),
            Opcode::VectorAbs16 => vbasic::emit_vector_abs16(ctx, ra, inst_ref, inst),
            Opcode::VectorAbs32 => vbasic::emit_vector_abs32(ctx, ra, inst_ref, inst),
            Opcode::VectorAbs64 => vbasic::emit_vector_abs64(ctx, ra, inst_ref, inst),
            Opcode::ZeroVector => vbasic::emit_zero_vector(ctx, ra, inst_ref, inst),
            Opcode::VectorZeroUpper => vbasic::emit_vector_zero_upper(ctx, ra, inst_ref, inst),
            Opcode::VectorCountLeadingZeros8 => vbasic::emit_vector_clz8(ctx, ra, inst_ref, inst),
            Opcode::VectorCountLeadingZeros16 => vbasic::emit_vector_clz16(ctx, ra, inst_ref, inst),
            Opcode::VectorCountLeadingZeros32 => vbasic::emit_vector_clz32(ctx, ra, inst_ref, inst),
            Opcode::VectorPopulationCount => vbasic::emit_vector_popcount(ctx, ra, inst_ref, inst),
            Opcode::VectorReverseBits => vbasic::emit_vector_reverse_bits(ctx, ra, inst_ref, inst),
            Opcode::VectorReverseElementsInHalfGroups8 => vbasic::emit_vector_reverse_half_groups_8(ctx, ra, inst_ref, inst),
            Opcode::VectorReverseElementsInWordGroups8 => vbasic::emit_vector_reverse_word_groups_8(ctx, ra, inst_ref, inst),
            Opcode::VectorReverseElementsInWordGroups16 => vbasic::emit_vector_reverse_word_groups_16(ctx, ra, inst_ref, inst),
            Opcode::VectorReverseElementsInLongGroups8 => vbasic::emit_vector_reverse_long_groups_8(ctx, ra, inst_ref, inst),
            Opcode::VectorReverseElementsInLongGroups16 => vbasic::emit_vector_reverse_long_groups_16(ctx, ra, inst_ref, inst),
            Opcode::VectorReverseElementsInLongGroups32 => vbasic::emit_vector_reverse_long_groups_32(ctx, ra, inst_ref, inst),

            // --- Vector compare ---
            Opcode::VectorEqual8 => vcmp::emit_vector_equal8(ctx, ra, inst_ref, inst),
            Opcode::VectorEqual16 => vcmp::emit_vector_equal16(ctx, ra, inst_ref, inst),
            Opcode::VectorEqual32 => vcmp::emit_vector_equal32(ctx, ra, inst_ref, inst),
            Opcode::VectorEqual64 => vcmp::emit_vector_equal64(ctx, ra, inst_ref, inst),
            Opcode::VectorEqual128 => vcmp::emit_vector_equal128(ctx, ra, inst_ref, inst),
            Opcode::VectorGreaterSigned8 => vcmp::emit_vector_greater_signed8(ctx, ra, inst_ref, inst),
            Opcode::VectorGreaterSigned16 => vcmp::emit_vector_greater_signed16(ctx, ra, inst_ref, inst),
            Opcode::VectorGreaterSigned32 => vcmp::emit_vector_greater_signed32(ctx, ra, inst_ref, inst),
            Opcode::VectorGreaterSigned64 => vcmp::emit_vector_greater_signed64(ctx, ra, inst_ref, inst),
            Opcode::VectorGreaterEqualSigned8 => vcmp::emit_vector_greater_equal_signed8(ctx, ra, inst_ref, inst),
            Opcode::VectorGreaterEqualSigned16 => vcmp::emit_vector_greater_equal_signed16(ctx, ra, inst_ref, inst),
            Opcode::VectorGreaterEqualSigned32 => vcmp::emit_vector_greater_equal_signed32(ctx, ra, inst_ref, inst),
            Opcode::VectorGreaterEqualSigned64 => vcmp::emit_vector_greater_equal_signed64(ctx, ra, inst_ref, inst),
            Opcode::VectorGreaterEqualUnsigned8 => vcmp::emit_vector_greater_equal_unsigned8(ctx, ra, inst_ref, inst),
            Opcode::VectorGreaterEqualUnsigned16 => vcmp::emit_vector_greater_equal_unsigned16(ctx, ra, inst_ref, inst),
            Opcode::VectorGreaterEqualUnsigned32 => vcmp::emit_vector_greater_equal_unsigned32(ctx, ra, inst_ref, inst),
            Opcode::VectorGreaterEqualUnsigned64 => vcmp::emit_vector_greater_equal_unsigned64(ctx, ra, inst_ref, inst),
            Opcode::VectorMinSigned8 => vcmp::emit_vector_min_signed8(ctx, ra, inst_ref, inst),
            Opcode::VectorMinSigned16 => vcmp::emit_vector_min_signed16(ctx, ra, inst_ref, inst),
            Opcode::VectorMinSigned32 => vcmp::emit_vector_min_signed32(ctx, ra, inst_ref, inst),
            Opcode::VectorMinSigned64 => vcmp::emit_vector_min_signed64(ctx, ra, inst_ref, inst),
            Opcode::VectorMaxSigned8 => vcmp::emit_vector_max_signed8(ctx, ra, inst_ref, inst),
            Opcode::VectorMaxSigned16 => vcmp::emit_vector_max_signed16(ctx, ra, inst_ref, inst),
            Opcode::VectorMaxSigned32 => vcmp::emit_vector_max_signed32(ctx, ra, inst_ref, inst),
            Opcode::VectorMaxSigned64 => vcmp::emit_vector_max_signed64(ctx, ra, inst_ref, inst),
            Opcode::VectorMinUnsigned8 => vcmp::emit_vector_min_unsigned8(ctx, ra, inst_ref, inst),
            Opcode::VectorMinUnsigned16 => vcmp::emit_vector_min_unsigned16(ctx, ra, inst_ref, inst),
            Opcode::VectorMinUnsigned32 => vcmp::emit_vector_min_unsigned32(ctx, ra, inst_ref, inst),
            Opcode::VectorMinUnsigned64 => vcmp::emit_vector_min_unsigned64(ctx, ra, inst_ref, inst),
            Opcode::VectorMaxUnsigned8 => vcmp::emit_vector_max_unsigned8(ctx, ra, inst_ref, inst),
            Opcode::VectorMaxUnsigned16 => vcmp::emit_vector_max_unsigned16(ctx, ra, inst_ref, inst),
            Opcode::VectorMaxUnsigned32 => vcmp::emit_vector_max_unsigned32(ctx, ra, inst_ref, inst),
            Opcode::VectorMaxUnsigned64 => vcmp::emit_vector_max_unsigned64(ctx, ra, inst_ref, inst),

            // --- Vector shift ---
            Opcode::VectorLogicalShiftLeft8 => vshift::emit_vector_logical_shift_left8(ctx, ra, inst_ref, inst),
            Opcode::VectorLogicalShiftLeft16 => vshift::emit_vector_logical_shift_left16(ctx, ra, inst_ref, inst),
            Opcode::VectorLogicalShiftLeft32 => vshift::emit_vector_logical_shift_left32(ctx, ra, inst_ref, inst),
            Opcode::VectorLogicalShiftLeft64 => vshift::emit_vector_logical_shift_left64(ctx, ra, inst_ref, inst),
            Opcode::VectorLogicalShiftRight8 => vshift::emit_vector_logical_shift_right8(ctx, ra, inst_ref, inst),
            Opcode::VectorLogicalShiftRight16 => vshift::emit_vector_logical_shift_right16(ctx, ra, inst_ref, inst),
            Opcode::VectorLogicalShiftRight32 => vshift::emit_vector_logical_shift_right32(ctx, ra, inst_ref, inst),
            Opcode::VectorLogicalShiftRight64 => vshift::emit_vector_logical_shift_right64(ctx, ra, inst_ref, inst),
            Opcode::VectorArithmeticShiftRight8 => vshift::emit_vector_arithmetic_shift_right8(ctx, ra, inst_ref, inst),
            Opcode::VectorArithmeticShiftRight16 => vshift::emit_vector_arithmetic_shift_right16(ctx, ra, inst_ref, inst),
            Opcode::VectorArithmeticShiftRight32 => vshift::emit_vector_arithmetic_shift_right32(ctx, ra, inst_ref, inst),
            Opcode::VectorArithmeticShiftRight64 => vshift::emit_vector_arithmetic_shift_right64(ctx, ra, inst_ref, inst),
            Opcode::VectorLogicalVShift8 => vshift::emit_vector_logical_vshift8(ctx, ra, inst_ref, inst),
            Opcode::VectorLogicalVShift16 => vshift::emit_vector_logical_vshift16(ctx, ra, inst_ref, inst),
            Opcode::VectorLogicalVShift32 => vshift::emit_vector_logical_vshift32(ctx, ra, inst_ref, inst),
            Opcode::VectorLogicalVShift64 => vshift::emit_vector_logical_vshift64(ctx, ra, inst_ref, inst),
            Opcode::VectorArithmeticVShift8 => vshift::emit_vector_arithmetic_vshift8(ctx, ra, inst_ref, inst),
            Opcode::VectorArithmeticVShift16 => vshift::emit_vector_arithmetic_vshift16(ctx, ra, inst_ref, inst),
            Opcode::VectorArithmeticVShift32 => vshift::emit_vector_arithmetic_vshift32(ctx, ra, inst_ref, inst),
            Opcode::VectorArithmeticVShift64 => vshift::emit_vector_arithmetic_vshift64(ctx, ra, inst_ref, inst),
            Opcode::VectorRoundingShiftLeftSigned8 => vshift::emit_vector_rounding_shift_left_signed8(ctx, ra, inst_ref, inst),
            Opcode::VectorRoundingShiftLeftSigned16 => vshift::emit_vector_rounding_shift_left_signed16(ctx, ra, inst_ref, inst),
            Opcode::VectorRoundingShiftLeftSigned32 => vshift::emit_vector_rounding_shift_left_signed32(ctx, ra, inst_ref, inst),
            Opcode::VectorRoundingShiftLeftSigned64 => vshift::emit_vector_rounding_shift_left_signed64(ctx, ra, inst_ref, inst),
            Opcode::VectorRoundingShiftLeftUnsigned8 => vshift::emit_vector_rounding_shift_left_unsigned8(ctx, ra, inst_ref, inst),
            Opcode::VectorRoundingShiftLeftUnsigned16 => vshift::emit_vector_rounding_shift_left_unsigned16(ctx, ra, inst_ref, inst),
            Opcode::VectorRoundingShiftLeftUnsigned32 => vshift::emit_vector_rounding_shift_left_unsigned32(ctx, ra, inst_ref, inst),
            Opcode::VectorRoundingShiftLeftUnsigned64 => vshift::emit_vector_rounding_shift_left_unsigned64(ctx, ra, inst_ref, inst),

            // --- Vector multiply ---
            Opcode::VectorMultiply8 => vmul::emit_vector_multiply8(ctx, ra, inst_ref, inst),
            Opcode::VectorMultiply16 => vmul::emit_vector_multiply16(ctx, ra, inst_ref, inst),
            Opcode::VectorMultiply32 => vmul::emit_vector_multiply32(ctx, ra, inst_ref, inst),
            Opcode::VectorMultiply64 => vmul::emit_vector_multiply64(ctx, ra, inst_ref, inst),
            Opcode::VectorMultiplySignedWiden8 => vmul::emit_vector_multiply_signed_widen8(ctx, ra, inst_ref, inst),
            Opcode::VectorMultiplySignedWiden16 => vmul::emit_vector_multiply_signed_widen16(ctx, ra, inst_ref, inst),
            Opcode::VectorMultiplySignedWiden32 => vmul::emit_vector_multiply_signed_widen32(ctx, ra, inst_ref, inst),
            Opcode::VectorMultiplyUnsignedWiden8 => vmul::emit_vector_multiply_unsigned_widen8(ctx, ra, inst_ref, inst),
            Opcode::VectorMultiplyUnsignedWiden16 => vmul::emit_vector_multiply_unsigned_widen16(ctx, ra, inst_ref, inst),
            Opcode::VectorMultiplyUnsignedWiden32 => vmul::emit_vector_multiply_unsigned_widen32(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedMultiplyLong16 => vmul::emit_vector_signed_multiply_long16(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedMultiplyLong32 => vmul::emit_vector_signed_multiply_long32(ctx, ra, inst_ref, inst),
            Opcode::VectorUnsignedMultiplyLong16 => vmul::emit_vector_unsigned_multiply_long16(ctx, ra, inst_ref, inst),
            Opcode::VectorUnsignedMultiplyLong32 => vmul::emit_vector_unsigned_multiply_long32(ctx, ra, inst_ref, inst),
            Opcode::VectorPolynomialMultiply8 => vmul::emit_vector_polynomial_multiply8(ctx, ra, inst_ref, inst),
            Opcode::VectorPolynomialMultiplyLong8 => vmul::emit_vector_polynomial_multiply_long8(ctx, ra, inst_ref, inst),
            Opcode::VectorPolynomialMultiplyLong64 => vmul::emit_vector_polynomial_multiply_long64(ctx, ra, inst_ref, inst),
            Opcode::VectorPairedAdd8 => vmul::emit_vector_paired_add8(ctx, ra, inst_ref, inst),
            Opcode::VectorPairedAdd16 => vmul::emit_vector_paired_add16(ctx, ra, inst_ref, inst),
            Opcode::VectorPairedAdd32 => vmul::emit_vector_paired_add32(ctx, ra, inst_ref, inst),
            Opcode::VectorPairedAdd64 => vmul::emit_vector_paired_add64(ctx, ra, inst_ref, inst),
            Opcode::VectorPairedAddLower8 => vmul::emit_vector_paired_add_lower8(ctx, ra, inst_ref, inst),
            Opcode::VectorPairedAddLower16 => vmul::emit_vector_paired_add_lower16(ctx, ra, inst_ref, inst),
            Opcode::VectorPairedAddLower32 => vmul::emit_vector_paired_add_lower32(ctx, ra, inst_ref, inst),
            Opcode::VectorPairedAddSignedWiden8 => vmul::emit_vector_paired_add_signed_widen8(ctx, ra, inst_ref, inst),
            Opcode::VectorPairedAddSignedWiden16 => vmul::emit_vector_paired_add_signed_widen16(ctx, ra, inst_ref, inst),
            Opcode::VectorPairedAddSignedWiden32 => vmul::emit_vector_paired_add_signed_widen32(ctx, ra, inst_ref, inst),
            Opcode::VectorPairedAddUnsignedWiden8 => vmul::emit_vector_paired_add_unsigned_widen8(ctx, ra, inst_ref, inst),
            Opcode::VectorPairedAddUnsignedWiden16 => vmul::emit_vector_paired_add_unsigned_widen16(ctx, ra, inst_ref, inst),
            Opcode::VectorPairedAddUnsignedWiden32 => vmul::emit_vector_paired_add_unsigned_widen32(ctx, ra, inst_ref, inst),
            Opcode::VectorPairedMaxSigned8 => vmul::emit_vector_paired_max_signed8(ctx, ra, inst_ref, inst),
            Opcode::VectorPairedMaxSigned16 => vmul::emit_vector_paired_max_signed16(ctx, ra, inst_ref, inst),
            Opcode::VectorPairedMaxSigned32 => vmul::emit_vector_paired_max_signed32(ctx, ra, inst_ref, inst),
            Opcode::VectorPairedMaxUnsigned8 => vmul::emit_vector_paired_max_unsigned8(ctx, ra, inst_ref, inst),
            Opcode::VectorPairedMaxUnsigned16 => vmul::emit_vector_paired_max_unsigned16(ctx, ra, inst_ref, inst),
            Opcode::VectorPairedMaxUnsigned32 => vmul::emit_vector_paired_max_unsigned32(ctx, ra, inst_ref, inst),
            Opcode::VectorPairedMinSigned8 => vmul::emit_vector_paired_min_signed8(ctx, ra, inst_ref, inst),
            Opcode::VectorPairedMinSigned16 => vmul::emit_vector_paired_min_signed16(ctx, ra, inst_ref, inst),
            Opcode::VectorPairedMinSigned32 => vmul::emit_vector_paired_min_signed32(ctx, ra, inst_ref, inst),
            Opcode::VectorPairedMinUnsigned8 => vmul::emit_vector_paired_min_unsigned8(ctx, ra, inst_ref, inst),
            Opcode::VectorPairedMinUnsigned16 => vmul::emit_vector_paired_min_unsigned16(ctx, ra, inst_ref, inst),
            Opcode::VectorPairedMinUnsigned32 => vmul::emit_vector_paired_min_unsigned32(ctx, ra, inst_ref, inst),

            // --- Vector arrangement ---
            Opcode::VectorGetElement8 => varr::emit_vector_get_element8(ctx, ra, inst_ref, inst),
            Opcode::VectorGetElement16 => varr::emit_vector_get_element16(ctx, ra, inst_ref, inst),
            Opcode::VectorGetElement32 => varr::emit_vector_get_element32(ctx, ra, inst_ref, inst),
            Opcode::VectorGetElement64 => varr::emit_vector_get_element64(ctx, ra, inst_ref, inst),
            Opcode::VectorSetElement8 => varr::emit_vector_set_element8(ctx, ra, inst_ref, inst),
            Opcode::VectorSetElement16 => varr::emit_vector_set_element16(ctx, ra, inst_ref, inst),
            Opcode::VectorSetElement32 => varr::emit_vector_set_element32(ctx, ra, inst_ref, inst),
            Opcode::VectorSetElement64 => varr::emit_vector_set_element64(ctx, ra, inst_ref, inst),
            Opcode::VectorBroadcast8 => varr::emit_vector_broadcast8(ctx, ra, inst_ref, inst),
            Opcode::VectorBroadcast16 => varr::emit_vector_broadcast16(ctx, ra, inst_ref, inst),
            Opcode::VectorBroadcast32 => varr::emit_vector_broadcast32(ctx, ra, inst_ref, inst),
            Opcode::VectorBroadcast64 => varr::emit_vector_broadcast64(ctx, ra, inst_ref, inst),
            Opcode::VectorBroadcastLower8 => varr::emit_vector_broadcast_lower8(ctx, ra, inst_ref, inst),
            Opcode::VectorBroadcastLower16 => varr::emit_vector_broadcast_lower16(ctx, ra, inst_ref, inst),
            Opcode::VectorBroadcastLower32 => varr::emit_vector_broadcast_lower32(ctx, ra, inst_ref, inst),
            Opcode::VectorExtract => varr::emit_vector_extract(ctx, ra, inst_ref, inst),
            Opcode::VectorExtractLower => varr::emit_vector_extract_lower(ctx, ra, inst_ref, inst),
            Opcode::VectorInterleaveLower8 => varr::emit_vector_interleave_lower8(ctx, ra, inst_ref, inst),
            Opcode::VectorInterleaveLower16 => varr::emit_vector_interleave_lower16(ctx, ra, inst_ref, inst),
            Opcode::VectorInterleaveLower32 => varr::emit_vector_interleave_lower32(ctx, ra, inst_ref, inst),
            Opcode::VectorInterleaveLower64 => varr::emit_vector_interleave_lower64(ctx, ra, inst_ref, inst),
            Opcode::VectorInterleaveUpper8 => varr::emit_vector_interleave_upper8(ctx, ra, inst_ref, inst),
            Opcode::VectorInterleaveUpper16 => varr::emit_vector_interleave_upper16(ctx, ra, inst_ref, inst),
            Opcode::VectorInterleaveUpper32 => varr::emit_vector_interleave_upper32(ctx, ra, inst_ref, inst),
            Opcode::VectorInterleaveUpper64 => varr::emit_vector_interleave_upper64(ctx, ra, inst_ref, inst),
            Opcode::VectorDeinterleaveEven8 => varr::emit_vector_deinterleave_even8(ctx, ra, inst_ref, inst),
            Opcode::VectorDeinterleaveEven16 => varr::emit_vector_deinterleave_even16(ctx, ra, inst_ref, inst),
            Opcode::VectorDeinterleaveEven32 => varr::emit_vector_deinterleave_even32(ctx, ra, inst_ref, inst),
            Opcode::VectorDeinterleaveEven64 => varr::emit_vector_deinterleave_even64(ctx, ra, inst_ref, inst),
            Opcode::VectorDeinterleaveOdd8 => varr::emit_vector_deinterleave_odd8(ctx, ra, inst_ref, inst),
            Opcode::VectorDeinterleaveOdd16 => varr::emit_vector_deinterleave_odd16(ctx, ra, inst_ref, inst),
            Opcode::VectorDeinterleaveOdd32 => varr::emit_vector_deinterleave_odd32(ctx, ra, inst_ref, inst),
            Opcode::VectorDeinterleaveOdd64 => varr::emit_vector_deinterleave_odd64(ctx, ra, inst_ref, inst),
            Opcode::VectorTranspose8 => varr::emit_vector_transpose8(ctx, ra, inst_ref, inst),
            Opcode::VectorTranspose16 => varr::emit_vector_transpose16(ctx, ra, inst_ref, inst),
            Opcode::VectorTranspose32 => varr::emit_vector_transpose32(ctx, ra, inst_ref, inst),
            Opcode::VectorTranspose64 => varr::emit_vector_transpose64(ctx, ra, inst_ref, inst),
            Opcode::VectorShuffleWords => varr::emit_vector_shuffle_words(ctx, ra, inst_ref, inst),
            Opcode::VectorShuffleHighHalfwords => varr::emit_vector_shuffle_high_halfwords(ctx, ra, inst_ref, inst),
            Opcode::VectorShuffleLowHalfwords => varr::emit_vector_shuffle_low_halfwords(ctx, ra, inst_ref, inst),
            Opcode::VectorNarrow16 => varr::emit_vector_narrow16(ctx, ra, inst_ref, inst),
            Opcode::VectorNarrow32 => varr::emit_vector_narrow32(ctx, ra, inst_ref, inst),
            Opcode::VectorNarrow64 => varr::emit_vector_narrow64(ctx, ra, inst_ref, inst),
            Opcode::VectorSignExtend8 => varr::emit_vector_sign_extend8(ctx, ra, inst_ref, inst),
            Opcode::VectorSignExtend16 => varr::emit_vector_sign_extend16(ctx, ra, inst_ref, inst),
            Opcode::VectorSignExtend32 => varr::emit_vector_sign_extend32(ctx, ra, inst_ref, inst),
            Opcode::VectorSignExtend64 => varr::emit_vector_sign_extend64(ctx, ra, inst_ref, inst),
            Opcode::VectorZeroExtend8 => varr::emit_vector_zero_extend8(ctx, ra, inst_ref, inst),
            Opcode::VectorZeroExtend16 => varr::emit_vector_zero_extend16(ctx, ra, inst_ref, inst),
            Opcode::VectorZeroExtend32 => varr::emit_vector_zero_extend32(ctx, ra, inst_ref, inst),
            Opcode::VectorZeroExtend64 => varr::emit_vector_zero_extend64(ctx, ra, inst_ref, inst),

            // --- Vector saturated ---
            Opcode::VectorSignedSaturatedAbs8 => vsat::emit_vector_signed_saturated_abs8(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedSaturatedAbs16 => vsat::emit_vector_signed_saturated_abs16(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedSaturatedAbs32 => vsat::emit_vector_signed_saturated_abs32(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedSaturatedAbs64 => vsat::emit_vector_signed_saturated_abs64(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedSaturatedNeg8 => vsat::emit_vector_signed_saturated_neg8(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedSaturatedNeg16 => vsat::emit_vector_signed_saturated_neg16(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedSaturatedNeg32 => vsat::emit_vector_signed_saturated_neg32(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedSaturatedNeg64 => vsat::emit_vector_signed_saturated_neg64(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedSaturatedAccumulateUnsigned8 => vsat::emit_vector_signed_saturated_accumulate_unsigned8(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedSaturatedAccumulateUnsigned16 => vsat::emit_vector_signed_saturated_accumulate_unsigned16(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedSaturatedAccumulateUnsigned32 => vsat::emit_vector_signed_saturated_accumulate_unsigned32(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedSaturatedAccumulateUnsigned64 => vsat::emit_vector_signed_saturated_accumulate_unsigned64(ctx, ra, inst_ref, inst),
            Opcode::VectorUnsignedSaturatedAccumulateSigned8 => vsat::emit_vector_unsigned_saturated_accumulate_signed8(ctx, ra, inst_ref, inst),
            Opcode::VectorUnsignedSaturatedAccumulateSigned16 => vsat::emit_vector_unsigned_saturated_accumulate_signed16(ctx, ra, inst_ref, inst),
            Opcode::VectorUnsignedSaturatedAccumulateSigned32 => vsat::emit_vector_unsigned_saturated_accumulate_signed32(ctx, ra, inst_ref, inst),
            Opcode::VectorUnsignedSaturatedAccumulateSigned64 => vsat::emit_vector_unsigned_saturated_accumulate_signed64(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedSaturatedNarrowToSigned16 => vsat::emit_vector_signed_saturated_narrow_to_signed16(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedSaturatedNarrowToSigned32 => vsat::emit_vector_signed_saturated_narrow_to_signed32(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedSaturatedNarrowToSigned64 => vsat::emit_vector_signed_saturated_narrow_to_signed64(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedSaturatedNarrowToUnsigned16 => vsat::emit_vector_signed_saturated_narrow_to_unsigned16(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedSaturatedNarrowToUnsigned32 => vsat::emit_vector_signed_saturated_narrow_to_unsigned32(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedSaturatedNarrowToUnsigned64 => vsat::emit_vector_signed_saturated_narrow_to_unsigned64(ctx, ra, inst_ref, inst),
            Opcode::VectorUnsignedSaturatedNarrow16 => vsat::emit_vector_unsigned_saturated_narrow16(ctx, ra, inst_ref, inst),
            Opcode::VectorUnsignedSaturatedNarrow32 => vsat::emit_vector_unsigned_saturated_narrow32(ctx, ra, inst_ref, inst),
            Opcode::VectorUnsignedSaturatedNarrow64 => vsat::emit_vector_unsigned_saturated_narrow64(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedSaturatedShiftLeft8 => vsat::emit_vector_signed_saturated_shift_left8(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedSaturatedShiftLeft16 => vsat::emit_vector_signed_saturated_shift_left16(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedSaturatedShiftLeft32 => vsat::emit_vector_signed_saturated_shift_left32(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedSaturatedShiftLeft64 => vsat::emit_vector_signed_saturated_shift_left64(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedSaturatedShiftLeftUnsigned8 => vsat::emit_vector_signed_saturated_shift_left_unsigned8(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedSaturatedShiftLeftUnsigned16 => vsat::emit_vector_signed_saturated_shift_left_unsigned16(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedSaturatedShiftLeftUnsigned32 => vsat::emit_vector_signed_saturated_shift_left_unsigned32(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedSaturatedShiftLeftUnsigned64 => vsat::emit_vector_signed_saturated_shift_left_unsigned64(ctx, ra, inst_ref, inst),
            Opcode::VectorUnsignedSaturatedShiftLeft8 => vsat::emit_vector_unsigned_saturated_shift_left8(ctx, ra, inst_ref, inst),
            Opcode::VectorUnsignedSaturatedShiftLeft16 => vsat::emit_vector_unsigned_saturated_shift_left16(ctx, ra, inst_ref, inst),
            Opcode::VectorUnsignedSaturatedShiftLeft32 => vsat::emit_vector_unsigned_saturated_shift_left32(ctx, ra, inst_ref, inst),
            Opcode::VectorUnsignedSaturatedShiftLeft64 => vsat::emit_vector_unsigned_saturated_shift_left64(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedSaturatedDoublingMultiplyHigh16 => vsat::emit_vector_signed_saturated_doubling_multiply_high16(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedSaturatedDoublingMultiplyHigh32 => vsat::emit_vector_signed_saturated_doubling_multiply_high32(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedSaturatedDoublingMultiplyHighRounding16 => vsat::emit_vector_signed_saturated_doubling_multiply_high_rounding16(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedSaturatedDoublingMultiplyHighRounding32 => vsat::emit_vector_signed_saturated_doubling_multiply_high_rounding32(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedSaturatedDoublingMultiplyLong16 => vsat::emit_vector_signed_saturated_doubling_multiply_long16(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedSaturatedDoublingMultiplyLong32 => vsat::emit_vector_signed_saturated_doubling_multiply_long32(ctx, ra, inst_ref, inst),
            Opcode::VectorHalvingAddSigned8 => vsat::emit_vector_halving_add_signed8(ctx, ra, inst_ref, inst),
            Opcode::VectorHalvingAddSigned16 => vsat::emit_vector_halving_add_signed16(ctx, ra, inst_ref, inst),
            Opcode::VectorHalvingAddSigned32 => vsat::emit_vector_halving_add_signed32(ctx, ra, inst_ref, inst),
            Opcode::VectorHalvingAddUnsigned8 => vsat::emit_vector_halving_add_unsigned8(ctx, ra, inst_ref, inst),
            Opcode::VectorHalvingAddUnsigned16 => vsat::emit_vector_halving_add_unsigned16(ctx, ra, inst_ref, inst),
            Opcode::VectorHalvingAddUnsigned32 => vsat::emit_vector_halving_add_unsigned32(ctx, ra, inst_ref, inst),
            Opcode::VectorHalvingSubSigned8 => vsat::emit_vector_halving_sub_signed8(ctx, ra, inst_ref, inst),
            Opcode::VectorHalvingSubSigned16 => vsat::emit_vector_halving_sub_signed16(ctx, ra, inst_ref, inst),
            Opcode::VectorHalvingSubSigned32 => vsat::emit_vector_halving_sub_signed32(ctx, ra, inst_ref, inst),
            Opcode::VectorHalvingSubUnsigned8 => vsat::emit_vector_halving_sub_unsigned8(ctx, ra, inst_ref, inst),
            Opcode::VectorHalvingSubUnsigned16 => vsat::emit_vector_halving_sub_unsigned16(ctx, ra, inst_ref, inst),
            Opcode::VectorHalvingSubUnsigned32 => vsat::emit_vector_halving_sub_unsigned32(ctx, ra, inst_ref, inst),

            // --- Vector misc ---
            Opcode::VectorSignedAbsoluteDifference8 => vmisc::emit_vector_signed_absolute_difference8(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedAbsoluteDifference16 => vmisc::emit_vector_signed_absolute_difference16(ctx, ra, inst_ref, inst),
            Opcode::VectorSignedAbsoluteDifference32 => vmisc::emit_vector_signed_absolute_difference32(ctx, ra, inst_ref, inst),
            Opcode::VectorUnsignedAbsoluteDifference8 => vmisc::emit_vector_unsigned_absolute_difference8(ctx, ra, inst_ref, inst),
            Opcode::VectorUnsignedAbsoluteDifference16 => vmisc::emit_vector_unsigned_absolute_difference16(ctx, ra, inst_ref, inst),
            Opcode::VectorUnsignedAbsoluteDifference32 => vmisc::emit_vector_unsigned_absolute_difference32(ctx, ra, inst_ref, inst),
            Opcode::VectorRoundingHalvingAddSigned8 => vmisc::emit_vector_rounding_halving_add_signed8(ctx, ra, inst_ref, inst),
            Opcode::VectorRoundingHalvingAddSigned16 => vmisc::emit_vector_rounding_halving_add_signed16(ctx, ra, inst_ref, inst),
            Opcode::VectorRoundingHalvingAddSigned32 => vmisc::emit_vector_rounding_halving_add_signed32(ctx, ra, inst_ref, inst),
            Opcode::VectorRoundingHalvingAddUnsigned8 => vmisc::emit_vector_rounding_halving_add_unsigned8(ctx, ra, inst_ref, inst),
            Opcode::VectorRoundingHalvingAddUnsigned16 => vmisc::emit_vector_rounding_halving_add_unsigned16(ctx, ra, inst_ref, inst),
            Opcode::VectorRoundingHalvingAddUnsigned32 => vmisc::emit_vector_rounding_halving_add_unsigned32(ctx, ra, inst_ref, inst),
            Opcode::VectorTable => vmisc::emit_vector_table(ctx, ra, inst_ref, inst),
            Opcode::VectorTableLookup64 => vmisc::emit_vector_table_lookup64(ctx, ra, inst_ref, inst),
            Opcode::VectorTableLookup128 => vmisc::emit_vector_table_lookup128(ctx, ra, inst_ref, inst),
            Opcode::VectorUnsignedRecipEstimate => vmisc::emit_vector_unsigned_recip_estimate(ctx, ra, inst_ref, inst),
            Opcode::VectorUnsignedRecipSqrtEstimate => vmisc::emit_vector_unsigned_recip_sqrt_estimate(ctx, ra, inst_ref, inst),

            // --- FP vector ---
            Opcode::FPVectorAdd32 => fpv::emit_fp_vector_add32(ctx, ra, inst_ref, inst),
            Opcode::FPVectorAdd64 => fpv::emit_fp_vector_add64(ctx, ra, inst_ref, inst),
            Opcode::FPVectorSub32 => fpv::emit_fp_vector_sub32(ctx, ra, inst_ref, inst),
            Opcode::FPVectorSub64 => fpv::emit_fp_vector_sub64(ctx, ra, inst_ref, inst),
            Opcode::FPVectorMul32 => fpv::emit_fp_vector_mul32(ctx, ra, inst_ref, inst),
            Opcode::FPVectorMul64 => fpv::emit_fp_vector_mul64(ctx, ra, inst_ref, inst),
            Opcode::FPVectorDiv32 => fpv::emit_fp_vector_div32(ctx, ra, inst_ref, inst),
            Opcode::FPVectorDiv64 => fpv::emit_fp_vector_div64(ctx, ra, inst_ref, inst),
            Opcode::FPVectorSqrt32 => fpv::emit_fp_vector_sqrt32(ctx, ra, inst_ref, inst),
            Opcode::FPVectorSqrt64 => fpv::emit_fp_vector_sqrt64(ctx, ra, inst_ref, inst),
            Opcode::FPVectorAbs16 => fpv::emit_fp_vector_abs16(ctx, ra, inst_ref, inst),
            Opcode::FPVectorAbs32 => fpv::emit_fp_vector_abs32(ctx, ra, inst_ref, inst),
            Opcode::FPVectorAbs64 => fpv::emit_fp_vector_abs64(ctx, ra, inst_ref, inst),
            Opcode::FPVectorNeg16 => fpv::emit_fp_vector_neg16(ctx, ra, inst_ref, inst),
            Opcode::FPVectorNeg32 => fpv::emit_fp_vector_neg32(ctx, ra, inst_ref, inst),
            Opcode::FPVectorNeg64 => fpv::emit_fp_vector_neg64(ctx, ra, inst_ref, inst),
            Opcode::FPVectorMax32 => fpv::emit_fp_vector_max32(ctx, ra, inst_ref, inst),
            Opcode::FPVectorMax64 => fpv::emit_fp_vector_max64(ctx, ra, inst_ref, inst),
            Opcode::FPVectorMin32 => fpv::emit_fp_vector_min32(ctx, ra, inst_ref, inst),
            Opcode::FPVectorMin64 => fpv::emit_fp_vector_min64(ctx, ra, inst_ref, inst),
            Opcode::FPVectorMaxNumeric32 => fpv::emit_fp_vector_max_numeric32(ctx, ra, inst_ref, inst),
            Opcode::FPVectorMaxNumeric64 => fpv::emit_fp_vector_max_numeric64(ctx, ra, inst_ref, inst),
            Opcode::FPVectorMinNumeric32 => fpv::emit_fp_vector_min_numeric32(ctx, ra, inst_ref, inst),
            Opcode::FPVectorMinNumeric64 => fpv::emit_fp_vector_min_numeric64(ctx, ra, inst_ref, inst),
            Opcode::FPVectorEqual16 => fpv::emit_fp_vector_equal16(ctx, ra, inst_ref, inst),
            Opcode::FPVectorEqual32 => fpv::emit_fp_vector_equal32(ctx, ra, inst_ref, inst),
            Opcode::FPVectorEqual64 => fpv::emit_fp_vector_equal64(ctx, ra, inst_ref, inst),
            Opcode::FPVectorGreater32 => fpv::emit_fp_vector_greater32(ctx, ra, inst_ref, inst),
            Opcode::FPVectorGreater64 => fpv::emit_fp_vector_greater64(ctx, ra, inst_ref, inst),
            Opcode::FPVectorGreaterEqual32 => fpv::emit_fp_vector_greater_equal32(ctx, ra, inst_ref, inst),
            Opcode::FPVectorGreaterEqual64 => fpv::emit_fp_vector_greater_equal64(ctx, ra, inst_ref, inst),
            Opcode::FPVectorMulX32 => fpv::emit_fp_vector_mulx32(ctx, ra, inst_ref, inst),
            Opcode::FPVectorMulX64 => fpv::emit_fp_vector_mulx64(ctx, ra, inst_ref, inst),
            Opcode::FPVectorPairedAdd32 => fpv::emit_fp_vector_paired_add32(ctx, ra, inst_ref, inst),
            Opcode::FPVectorPairedAdd64 => fpv::emit_fp_vector_paired_add64(ctx, ra, inst_ref, inst),
            Opcode::FPVectorPairedAddLower32 => fpv::emit_fp_vector_paired_add_lower32(ctx, ra, inst_ref, inst),
            Opcode::FPVectorPairedAddLower64 => fpv::emit_fp_vector_paired_add_lower64(ctx, ra, inst_ref, inst),

            // --- FP vector convert ---
            Opcode::FPVectorMulAdd16 => fpvc::emit_fp_vector_muladd16(ctx, ra, inst_ref, inst),
            Opcode::FPVectorMulAdd32 => fpvc::emit_fp_vector_muladd32(ctx, ra, inst_ref, inst),
            Opcode::FPVectorMulAdd64 => fpvc::emit_fp_vector_muladd64(ctx, ra, inst_ref, inst),
            Opcode::FPVectorRecipEstimate16 => fpvc::emit_fp_vector_recip_estimate16(ctx, ra, inst_ref, inst),
            Opcode::FPVectorRecipEstimate32 => fpvc::emit_fp_vector_recip_estimate32(ctx, ra, inst_ref, inst),
            Opcode::FPVectorRecipEstimate64 => fpvc::emit_fp_vector_recip_estimate64(ctx, ra, inst_ref, inst),
            Opcode::FPVectorRecipStepFused16 => fpvc::emit_fp_vector_recip_step_fused16(ctx, ra, inst_ref, inst),
            Opcode::FPVectorRecipStepFused32 => fpvc::emit_fp_vector_recip_step_fused32(ctx, ra, inst_ref, inst),
            Opcode::FPVectorRecipStepFused64 => fpvc::emit_fp_vector_recip_step_fused64(ctx, ra, inst_ref, inst),
            Opcode::FPVectorRSqrtEstimate16 => fpvc::emit_fp_vector_rsqrt_estimate16(ctx, ra, inst_ref, inst),
            Opcode::FPVectorRSqrtEstimate32 => fpvc::emit_fp_vector_rsqrt_estimate32(ctx, ra, inst_ref, inst),
            Opcode::FPVectorRSqrtEstimate64 => fpvc::emit_fp_vector_rsqrt_estimate64(ctx, ra, inst_ref, inst),
            Opcode::FPVectorRSqrtStepFused16 => fpvc::emit_fp_vector_rsqrt_step_fused16(ctx, ra, inst_ref, inst),
            Opcode::FPVectorRSqrtStepFused32 => fpvc::emit_fp_vector_rsqrt_step_fused32(ctx, ra, inst_ref, inst),
            Opcode::FPVectorRSqrtStepFused64 => fpvc::emit_fp_vector_rsqrt_step_fused64(ctx, ra, inst_ref, inst),
            Opcode::FPVectorRoundInt16 => fpvc::emit_fp_vector_round_int16(ctx, ra, inst_ref, inst),
            Opcode::FPVectorRoundInt32 => fpvc::emit_fp_vector_round_int32(ctx, ra, inst_ref, inst),
            Opcode::FPVectorRoundInt64 => fpvc::emit_fp_vector_round_int64(ctx, ra, inst_ref, inst),
            Opcode::FPVectorFromSignedFixed32 => fpvc::emit_fp_vector_from_signed_fixed32(ctx, ra, inst_ref, inst),
            Opcode::FPVectorFromSignedFixed64 => fpvc::emit_fp_vector_from_signed_fixed64(ctx, ra, inst_ref, inst),
            Opcode::FPVectorFromUnsignedFixed32 => fpvc::emit_fp_vector_from_unsigned_fixed32(ctx, ra, inst_ref, inst),
            Opcode::FPVectorFromUnsignedFixed64 => fpvc::emit_fp_vector_from_unsigned_fixed64(ctx, ra, inst_ref, inst),
            Opcode::FPVectorToSignedFixed16 => fpvc::emit_fp_vector_to_signed_fixed16(ctx, ra, inst_ref, inst),
            Opcode::FPVectorToSignedFixed32 => fpvc::emit_fp_vector_to_signed_fixed32(ctx, ra, inst_ref, inst),
            Opcode::FPVectorToSignedFixed64 => fpvc::emit_fp_vector_to_signed_fixed64(ctx, ra, inst_ref, inst),
            Opcode::FPVectorToUnsignedFixed16 => fpvc::emit_fp_vector_to_unsigned_fixed16(ctx, ra, inst_ref, inst),
            Opcode::FPVectorToUnsignedFixed32 => fpvc::emit_fp_vector_to_unsigned_fixed32(ctx, ra, inst_ref, inst),
            Opcode::FPVectorToUnsignedFixed64 => fpvc::emit_fp_vector_to_unsigned_fixed64(ctx, ra, inst_ref, inst),
            Opcode::FPVectorFromHalf32 => fpvc::emit_fp_vector_from_half32(ctx, ra, inst_ref, inst),
            Opcode::FPVectorToHalf32 => fpvc::emit_fp_vector_to_half32(ctx, ra, inst_ref, inst),

            // --- A32 context getters/setters ---
            Opcode::A32SetCheckBit => a32::emit_a32_set_check_bit(ctx, ra, inst_ref, inst),
            Opcode::A32GetCFlag => a32::emit_a32_get_c_flag(ctx, ra, inst_ref, inst),
            Opcode::A32GetRegister => a32::emit_a32_get_register(ctx, ra, inst_ref, inst),
            Opcode::A32SetRegister => a32::emit_a32_set_register(ctx, ra, inst_ref, inst),
            Opcode::A32GetExtendedRegister32 => a32::emit_a32_get_extended_register32(ctx, ra, inst_ref, inst),
            Opcode::A32GetExtendedRegister64 => a32::emit_a32_get_extended_register64(ctx, ra, inst_ref, inst),
            Opcode::A32SetExtendedRegister32 => a32::emit_a32_set_extended_register32(ctx, ra, inst_ref, inst),
            Opcode::A32SetExtendedRegister64 => a32::emit_a32_set_extended_register64(ctx, ra, inst_ref, inst),
            Opcode::A32GetVector => a32::emit_a32_get_vector(ctx, ra, inst_ref, inst),
            Opcode::A32SetVector => a32::emit_a32_set_vector(ctx, ra, inst_ref, inst),
            Opcode::A32GetCpsr => a32::emit_a32_get_cpsr(ctx, ra, inst_ref, inst),
            Opcode::A32SetCpsr => a32::emit_a32_set_cpsr(ctx, ra, inst_ref, inst),
            Opcode::A32SetCpsrNZCVRaw => a32::emit_a32_set_cpsr_nzcv_raw(ctx, ra, inst_ref, inst),
            Opcode::A32SetCpsrNZCV => a32::emit_a32_set_cpsr_nzcv(ctx, ra, inst_ref, inst),
            Opcode::A32SetCpsrNZCVQ => a32::emit_a32_set_cpsr_nzcvq(ctx, ra, inst_ref, inst),
            Opcode::A32SetCpsrNZ => a32::emit_a32_set_cpsr_nz(ctx, ra, inst_ref, inst),
            Opcode::A32SetCpsrNZC => a32::emit_a32_set_cpsr_nzc(ctx, ra, inst_ref, inst),
            Opcode::A32OrQFlag => a32::emit_a32_or_q_flag(ctx, ra, inst_ref, inst),
            Opcode::A32GetGEFlags => a32::emit_a32_get_ge_flags(ctx, ra, inst_ref, inst),
            Opcode::A32SetGEFlags => a32::emit_a32_set_ge_flags(ctx, ra, inst_ref, inst),
            Opcode::A32SetGEFlagsCompressed => a32::emit_a32_set_ge_flags_compressed(ctx, ra, inst_ref, inst),
            Opcode::A32BXWritePC => a32::emit_a32_bx_write_pc(ctx, ra, inst_ref, inst),
            Opcode::A32UpdateUpperLocationDescriptor => a32::emit_a32_update_upper_location_descriptor(ctx, ra, inst_ref, inst),
            Opcode::A32CallSupervisor => a32::emit_a32_call_supervisor(ctx, ra, inst_ref, inst),
            Opcode::A32ExceptionRaised => a32::emit_a32_exception_raised(ctx, ra, inst_ref, inst),
            Opcode::A32DataSynchronizationBarrier => a32::emit_a32_dsb(ctx, ra, inst_ref, inst),
            Opcode::A32DataMemoryBarrier => a32::emit_a32_dmb(ctx, ra, inst_ref, inst),
            Opcode::A32InstructionSynchronizationBarrier => a32::emit_a32_isb(ctx, ra, inst_ref, inst),
            Opcode::A32GetFpscr => a32::emit_a32_get_fpscr(ctx, ra, inst_ref, inst),
            Opcode::A32SetFpscr => a32::emit_a32_set_fpscr(ctx, ra, inst_ref, inst),
            Opcode::A32GetFpscrNZCV => a32::emit_a32_get_fpscr_nzcv(ctx, ra, inst_ref, inst),
            Opcode::A32SetFpscrNZCV => a32::emit_a32_set_fpscr_nzcv(ctx, ra, inst_ref, inst),

            // --- A32 Memory ---
            Opcode::A32ClearExclusive => a32::emit_a32_clear_exclusive(ctx, ra, inst_ref, inst),
            Opcode::A32ReadMemory8 => a32::emit_a32_read_memory_8(ctx, ra, inst_ref, inst),
            Opcode::A32ReadMemory16 => a32::emit_a32_read_memory_16(ctx, ra, inst_ref, inst),
            Opcode::A32ReadMemory32 => a32::emit_a32_read_memory_32(ctx, ra, inst_ref, inst),
            Opcode::A32ReadMemory64 => a32::emit_a32_read_memory_64(ctx, ra, inst_ref, inst),
            Opcode::A32ExclusiveReadMemory8 => a32::emit_a32_exclusive_read_memory_8(ctx, ra, inst_ref, inst),
            Opcode::A32ExclusiveReadMemory16 => a32::emit_a32_exclusive_read_memory_16(ctx, ra, inst_ref, inst),
            Opcode::A32ExclusiveReadMemory32 => a32::emit_a32_exclusive_read_memory_32(ctx, ra, inst_ref, inst),
            Opcode::A32ExclusiveReadMemory64 => a32::emit_a32_exclusive_read_memory_64(ctx, ra, inst_ref, inst),
            Opcode::A32WriteMemory8 => a32::emit_a32_write_memory_8(ctx, ra, inst_ref, inst),
            Opcode::A32WriteMemory16 => a32::emit_a32_write_memory_16(ctx, ra, inst_ref, inst),
            Opcode::A32WriteMemory32 => a32::emit_a32_write_memory_32(ctx, ra, inst_ref, inst),
            Opcode::A32WriteMemory64 => a32::emit_a32_write_memory_64(ctx, ra, inst_ref, inst),
            Opcode::A32ExclusiveWriteMemory8 => a32::emit_a32_exclusive_write_memory_8(ctx, ra, inst_ref, inst),
            Opcode::A32ExclusiveWriteMemory16 => a32::emit_a32_exclusive_write_memory_16(ctx, ra, inst_ref, inst),
            Opcode::A32ExclusiveWriteMemory32 => a32::emit_a32_exclusive_write_memory_32(ctx, ra, inst_ref, inst),
            Opcode::A32ExclusiveWriteMemory64 => a32::emit_a32_exclusive_write_memory_64(ctx, ra, inst_ref, inst),

            // --- A32 Coprocessor (stubs) ---
            Opcode::A32CoprocInternalOperation => a32::emit_a32_coproc_internal_operation(ctx, ra, inst_ref, inst),
            Opcode::A32CoprocSendOneWord => a32::emit_a32_coproc_send_one_word(ctx, ra, inst_ref, inst),
            Opcode::A32CoprocSendTwoWords => a32::emit_a32_coproc_send_two_words(ctx, ra, inst_ref, inst),
            Opcode::A32CoprocGetOneWord => a32::emit_a32_coproc_get_one_word(ctx, ra, inst_ref, inst),
            Opcode::A32CoprocGetTwoWords => a32::emit_a32_coproc_get_two_words(ctx, ra, inst_ref, inst),
            Opcode::A32CoprocLoadWords => a32::emit_a32_coproc_load_words(ctx, ra, inst_ref, inst),
            Opcode::A32CoprocStoreWords => a32::emit_a32_coproc_store_words(ctx, ra, inst_ref, inst),

            // --- Not yet implemented ---
            _ => {
                panic!("Opcode {:?} not handled in emission pipeline", inst.opcode);
            }
        }

        ra.end_of_alloc_scope();
    }

    // Emit the block terminal (control flow exit)
    emit_terminal::emit_terminal(ctx, ra, &block.terminal);

    BlockDescriptor {
        entrypoint_offset: start,
        size: ra.asm.size() - start,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_emit_block_exists() {
        // Type-check that emit_block has the right signature
        let _: fn(&EmitContext, &mut RegAlloc, &Block) -> BlockDescriptor = emit_block;
    }
}
